name: CMake

on: [ push ]

env:
    BUILD_TYPE: Debug

jobs:
    build-linux:
        name: Linux

        runs-on: ubuntu-latest

        strategy:
            matrix:
                target_arch: [ x86_64 ]

        steps:
            -   name: Clone repository
                uses: actions/checkout@v2

            -   name: Create Build Environment
                run: |
                    sudo apt-get install valgrind libcunit1-dev
                    cmake -E make_directory ${{github.workspace}}/build

            -   name: Configure CMake
                shell: bash
                working-directory: ${{github.workspace}}/build
                run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

            -   name: Build
                working-directory: ${{github.workspace}}/build
                shell: bash
                run: cmake --build . --config $BUILD_TYPE

            -   name: Test (With Valgrind)
                working-directory: ${{github.workspace}}/build
                shell: bash
                run: VALGRIND_OPTS='--leak-check=full --leak-resolution=med --track-origins=yes --show-leak-kinds=all --vgdb=no' valgrind ./lib-snowflakeid-test SINGLE

            -   name: Test (Performance)
                working-directory: ${{github.workspace}}/build
                shell: bash
                run: |
                    ./lib-snowflakeid-test PERFORMANCE 5000
                    ./lib-snowflakeid-test PERFORMANCE 100000
                    ./lib-snowflakeid-test PERFORMANCE 500000
                    ./lib-snowflakeid-test PERFORMANCE 1000000

    build-macos:
        name: MacOS

        runs-on: macos-latest

        strategy:
            matrix:
                target_arch: [ x86_64 ]

        steps:
            -   name: Clone repository
                uses: actions/checkout@v2

            -   name: Create Build Environment
                run: cmake -E make_directory ${{github.workspace}}/build

            -   name: Configure CMake
                shell: bash
                working-directory: ${{github.workspace}}/build
                run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

            -   name: Build
                working-directory: ${{github.workspace}}/build
                shell: bash
                run: cmake --build . --config $BUILD_TYPE

            -   name: Test
                working-directory: ${{github.workspace}}/build
                shell: bash
                run: ./lib-snowflakeid-test SINGLE

            -   name: Test (Performance)
                working-directory: ${{github.workspace}}/build
                shell: bash
                run: |
                    ./lib-snowflakeid-test PERFORMANCE 5000
                    ./lib-snowflakeid-test PERFORMANCE 100000
                    ./lib-snowflakeid-test PERFORMANCE 500000
                    ./lib-snowflakeid-test PERFORMANCE 1000000

    build-windows:
        name: Windows

        runs-on: windows-latest

        strategy:
            matrix:
                target_arch: [ amd64 ]

        steps:
            -   name: Clone repository
                uses: actions/checkout@v2

            -   name: Configure CMake
                run: mkdir build && cd build && cmake ..

            -   name: Build
                run: cmake --build build --config Debug

            -   name: Test
                working-directory: ${{github.workspace}}/build/Debug
                run: ./lib-snowflakeid-test.exe SINGLE

            -   name: Test (Performance)
                working-directory: ${{github.workspace}}/build/Debug
                run: |
                    ./lib-snowflakeid-test PERFORMANCE 5000
                    ./lib-snowflakeid-test PERFORMANCE 100000
                    ./lib-snowflakeid-test PERFORMANCE 500000
                    ./lib-snowflakeid-test PERFORMANCE 1000000
